name: slack-notification-release
env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
on:
  release:
    branches:
       - main
    types:
       - "*"

jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps:

      - name: Check slack
        uses: act10ns/slack@v1
        with:
           status: ${{ job.status }}
           channel: '#cloudrail-dev'
           message: Release body of ${{ github.ref }} ${{ env.user }}
                    ${{ github.event.commits[0].author.name }}
                    ${{ github.event.commits[0].message }}

        if: always()
